_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 17
                - 23
                - 55
            "4": 3.11.13
            "5": 0.18.7
            "8":
                - 5
            "10":
                - 3
            "12": 0.18.7
            "13": linux-x86_64
